### ISSUE TITLE
Base64 class not found

### ISSUE THREAD

**Issue by wildmaster84** [jeremynoesen/VolleyBall#24]
Paper 1.16.5
WorldEdit 7.2.8

Only plugin that is having issues with spawning armor stands on my server

![image](https://user-images.githubusercontent.com/46942741/181591610-3568edaf-6e28-49eb-94e8-ef58bcb70b3d.png)

**Comment by jeremynoesen** [comment]
Hey, thanks for letting me know! I want to say I have been aware of this issue and it has been fixed in the upcoming 1.2.0 update.

The main cause of this is Paper missing some libraries that come with regular Spigot. I plan to release the update within the next week, so for now please wait until then, or use Spigot for now.

**Comment by jeremynoesen** [comment]
See #5

**Comment by jeremynoesen** [comment]
See #5
